// Realistic Seattle-area resource data, grounded in real well-known orgs.
// Coordinates are approximate to the real service locations for map/distance use.
// Expanded 2026 with high-leverage system entry points + additional verified programs.
var SEATTLE_RESOURCES = [
  // ---- HIGH-LEVERAGE SYSTEM ENTRY POINTS (always list first) ----
  { id:'sys1', type:'system', name:'Washington 211 / Crisis Connections', hours:'Live specialists Mon–Fri 9am–5pm; automated & text 24/7', addr:'Phone & web service, King County', phone:'211 or (800) 621-4636', notes:'Primary navigation hub for all basic needs: shelter, food, benefits, legal, utility help. Text WAOD to 898211 for automated. Over 17,000 verified services. Start here for almost anything.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'sys2', type:'system', name:'King County Coordinated Entry (KCRHA) — Regional Access Points', hours:'Varies by RAP location; many appointment-only', addr:'Multiple RAPs across King County', phone:'See individual RAP or call 211', notes:'Single system that assesses and prioritizes people for limited housing resources (rapid rehousing, PSH, transitional). Access via any Regional Access Point. Does not guarantee immediate placement but is the required pathway for most housing programs.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'sys3', type:'system', name:'Family Emergency Shelter Access Line (Mary’s Place)', hours:'Daily starting 9:00am (call every day you need a bed)', addr:'Phone intake for families across King County', phone:'(206) 245-1026', notes:'Highest-leverage number for families with children seeking same-day or next-night emergency shelter. Call every day starting at 9am. Also coordinates many family shelter beds.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'sys4', type:'system', name:'Youth & Young Adult Emergency Access', hours:'Varies by program; several 24/7 or evening intake', addr:'Multiple YA programs', phone:'800-495-7802 (YouthCare main) or specific lines below', notes:'Central entry for ages ~12–24. Key programs: New Horizons (206-374-0866), ROOTS (206-632-1635), YouthCare Orion (206-622-5555), The Landing Redmond (425-449-3868).', free:true, lat:47.6062, lon:-122.3321 },
  { id:'sys5', type:'system', name:'Crisis Connections 24-Hour Crisis Line + 988', hours:'24/7', addr:'Phone service', phone:'(206) 461-3222 or 988', notes:'Emotional crisis, suicide support, substance concerns, or just need someone to talk to. Free and confidential. 988 is national; local line has King County knowledge.', free:true, lat:47.6062, lon:-122.3321 },

  // ---- Emergency overnight shelters ----
  { id:'r1', type:'shelter', name:'DESC Shelter — Downtown Emergency Service Center', hours:'Every night, doors 4:00pm–7:00am', addr:'517 3rd Ave, Seattle, WA', phone:'(206) 464-1570', notes:'Low-barrier overnight shelter for adults. No sobriety requirement. Case management on-site. Pet-friendly space available — ask at intake.', free:true, lat:47.6027, lon:-122.3305 , tags:['pet']},
  { id:'r2', type:'shelter', name:'Mary\'s Place Family Shelter', hours:'24/7 intake for families (via access line)', addr:'1830 9th Ave, Seattle, WA (and other sites)', phone:'(206) 245-1026', notes:'Shelter specifically for families with children. Call the Family Emergency Shelter Access Line every day starting 9am. Walk-ins also accepted at some sites.', free:true, lat:47.6156, lon:-122.3350 , tags:['family', 'hasKids']},
  { id:'r3', type:'shelter', name:'Plymouth Housing — Overnight Shelter', hours:'Every night, 6:00pm–7:00am', addr:'2400 3rd Ave, Seattle, WA', phone:'(206) 441-4540', notes:'Adult shelter with pathway to permanent supportive housing. Line forms early in winter.', free:true, lat:47.6152, lon:-122.3450 },
  { id:'r4', type:'shelter', name:'Compass Housing Alliance — Blaine Center', hours:'Every night, doors 6:30pm', addr:'2440 Boren Ave, Seattle, WA', phone:'(206) 474-1223', notes:'Men\'s overnight shelter with breakfast in the morning.', free:true, lat:47.6172, lon:-122.3283 },
  { id:'r62', type:'shelter', name:'Bread of Life Mission Shelter', hours:'Intake Mon–Fri 9am–3pm for overnight beds', addr:'97 S Main St, Seattle, WA', phone:'(206) 682-3579', notes:'Men\'s overnight shelter + day services. Meals, mail, lockers, showers, clothing. Chapel attendance historically required for some stays — confirm current policy. First nights often free.', free:true, lat:47.6005, lon:-122.3345 },
  { id:'r63', type:'shelter', name:'Operation Nightwatch', hours:'Dinner 8–9:15pm nightly; shelter referrals check-in ~7:45pm', addr:'302 14th Ave S, Seattle, WA', phone:'(206) 329-2099 (shelter); (206) 323-4359 (general)', notes:'Nightly meal for up to 150 people + limited shelter referrals (men nightly, women Mon–Fri). No ID required but helpful. Also permanent housing for seniors 62+.', free:true, lat:47.6018, lon:-122.3145 },
  { id:'r64', type:'shelter', name:'SHARE / WHEEL Self-Managed Shelters', hours:'Intake times vary by site (often evenings)', addr:'Multiple sites including Josephinum 1902 2nd Ave', phone:'Walk-in or (206) 448-7889 for storage/info', notes:'Self-managed overnight shelters at ~10 rotating/church sites for single adults 18+. Apply in person. Low-barrier, community-run model.', free:true, lat:47.6125, lon:-122.3390 },
  { id:'r65', type:'shelter', name:'St. Martin de Porres Shelter', hours:'24/7', addr:'1561 Alaskan Way S, Seattle, WA', phone:'(206) 323-6341 or (206) 622-7307', notes:'Emergency shelter for men ages 50+. Hot dinners, showers, laundry, hygiene. Service animals accepted. Call for intake.', free:true, lat:47.5810, lon:-122.3400 , tags:['senior']},
  { id:'r66', type:'shelter', name:'Noel House (YWCA)', hours:'24-hour phone; overnight shelter for women', addr:'Seattle (confirm current address via phone)', phone:'(206) 441-3210', notes:'Safe shelter for homeless women, especially the most vulnerable. Call for current intake process.', free:true, lat:47.6100, lon:-122.3400 },
  { id:'r67', type:'shelter', name:'Harborview Medical Respite', hours:'Referral-based, short-term', addr:'800 Jefferson St, Seattle, WA', phone:'(206) 744-5200', notes:'Short-term respite beds for homeless adults too sick for regular shelter, usually post-hospital. Medical support on-site.', free:false, lat:47.6045, lon:-122.3235 },
  { id:'r68', type:'shelter', name:'New Horizons Young Adult Shelter', hours:'Intake first-time around 9pm; daily', addr:'2709 3rd Ave, Seattle, WA', phone:'(206) 374-0866', notes:'Ages 18–25. Pets allowed. Showers, laundry, creative space, computers, clothing, meals, activities. Call or walk in.', free:true, lat:47.6175, lon:-122.3455 , tags:['youth']},
  { id:'r69', type:'shelter', name:'ROOTS Young Adult Shelter', hours:'Intake daily by phone or in-person 8–8:30pm', addr:'4541 19th Ave NE, Seattle, WA', phone:'(206) 632-1635', notes:'Ages 18–25. Hot breakfast & dinner, case management, health provider visits. State ID often required.', free:true, lat:47.6615, lon:-122.3070 , tags:['youth']},
  { id:'r70', type:'shelter', name:'YouthCare Orion Center (Day + Night)', hours:'Day program + overnight options; call for current', addr:'1828 Yale Ave, Seattle, WA', phone:'(206) 622-5555', notes:'Ages 12–24. Meals, showers, laundry, clothing, medical clinic, case management, legal aid, education/employment, housing connection. Drop-in day services strong.', free:true, lat:47.6170, lon:-122.3305 , tags:['youth']},
  { id:'r71', type:'shelter', name:'YouthCare South Seattle Shelter', hours:'Overnight 8pm–8:30am', addr:'9416 Rainier Ave S, Seattle, WA', phone:'(206) 331-2363', notes:'Ages 18–24. Meals, computers, laundry, showers, clothing, medical, pet food, lockers, case management, ID help, legal aid.', free:true, lat:47.5220, lon:-122.2700 , tags:['youth']},

  // ---- Tiny house villages / sanctioned encampments ----
  { id:'r5', type:'village', name:'LIHI Tiny House Village — Georgetown', hours:'24/7 for residents, intake varies', addr:'1000 S Myrtle St, Seattle, WA', phone:'(206) 620-7130', notes:'Low Income Housing Institute tiny house village. Case management on-site, referral often needed — call or ask an outreach worker to help you get on the list.', free:true, lat:47.5484, lon:-122.3210 },
  { id:'r6', type:'village', name:'LIHI Tiny House Village — Whittier Heights', hours:'24/7 for residents', addr:'8620 Fremont Ave N, Seattle, WA', phone:'(206) 620-7130', notes:'Pet-friendly tiny house village. Ask LIHI\'s central line about current openings.', free:true, lat:47.6910, lon:-122.3550 },
  { id:'r72', type:'village', name:'Nickelsville / Other LIHI & Community Villages', hours:'24/7 for residents; intake via outreach or LIHI', addr:'Multiple sites, Seattle area', phone:'(206) 620-7130 (LIHI) or (206) 856-1211', notes:'Community-run and LIHI-supported tiny house / sanctioned encampment sites. Meal programs and case management often on-site. Ask outreach workers for current openings.', free:true, lat:47.5600, lon:-122.3050 },

  // ---- Day centers ----
  { id:'r7', type:'daycenter', name:'DESC Day Center', hours:'Mon–Fri, 8:00am–4:00pm', addr:'517 3rd Ave, Seattle, WA', phone:'(206) 464-1570', notes:'Indoor space to rest, case management, restrooms. No appointment needed.', free:true, lat:47.6027, lon:-122.3305 },
  { id:'r8', type:'daycenter', name:'Urban Rest Stop (Downtown)', hours:'Mon–Fri 5:30/6:30am–4/8:30pm (confirm current); Sat–Sun shorter', addr:'1924/1925 9th Ave, Seattle, WA', phone:'(206) 623-6675 or (206) 332-0110', notes:'Showers, restrooms, laundry, mail, charging. Core hygiene hub. Same-day appointments typical.', free:true, lat:47.6165, lon:-122.3352 },
  { id:'r9', type:'daycenter', name:'Recovery Café Seattle', hours:'Mon–Fri, 8:30am–2:30pm', addr:'2022 Boren Ave, Seattle, WA', phone:'(206) 726-9050', notes:'Community space for people in or seeking recovery. Free coffee and meals, peer support circles.', free:true, lat:47.6178, lon:-122.3298 },
  { id:'r73', type:'daycenter', name:'Compass Multi-Service / Hygiene Center', hours:'Day Center Mon–Fri 9am–4pm; Hygiene Mon–Fri 8:30am–4pm + Sat 8am–12pm', addr:'210 Alaskan Way S (orange archway), Seattle, WA', phone:'(206) 474-1630 (day); (206) 474-1680 (hygiene)', notes:'Mail, case management, shelter/housing referral, showers, laundry, medical access, free lunch & dinner (lunch only Sat). Single adults 18+.', free:true, lat:47.6010, lon:-122.3355 },
  { id:'r74', type:'daycenter', name:'Angeline\'s Day Center (YWCA)', hours:'Mon–Fri ~10am–4pm', addr:'2030 3rd Ave, Seattle, WA', phone:'(206) 436-8650', notes:'Women only. Breakfast & lunch, laundry, showers, lockers, health & mental health counseling, phones/computers.', free:true, lat:47.6135, lon:-122.3420 , tags:['woman']},
  { id:'r75', type:'daycenter', name:'Chief Seattle Club Day Center', hours:'Typically 7am–2pm (confirm current remodel hours)', addr:'410 2nd Ave Ext S / 410 2nd Ave, Seattle, WA', phone:'(206) 715-7536', notes:'Primarily for Native American / Alaska Native adults. Meals, showers, laundry, mail, cultural programming, housing case management, health services. Membership/case manager model.', free:true, lat:47.6008, lon:-122.3325 , tags:['native']},
  { id:'r76', type:'daycenter', name:'Elizabeth Gregory Home Day Shelter', hours:'Drop-in daytime', addr:'1604 NE 50th St, Seattle, WA', phone:'(206) 729-0262', notes:'Women only. Case management, showers, laundry, health navigation, computers, mail.', free:true, lat:47.6650, lon:-122.3100 , tags:['woman']},
  { id:'r77', type:'daycenter', name:'Dave\'s Day Center (Immanuel Community Services)', hours:'Mon–Fri 8:00am–2:00pm (or noon–1:30pm depending on source)', addr:'1215 Thomas St, Seattle, WA', phone:'(206) 622-1930', notes:'Showers, laundry, toiletries, case management, resource connections, warm indoor space. All genders, adults.', free:true, lat:47.6205, lon:-122.3370 },
  { id:'r78', type:'daycenter', name:'Seattle Indian Center Day Center', hours:'Mon–Fri 9:00am–5:30/6:00pm', addr:'624 S Dearborn St or 1265 S Main St area, Seattle, WA', phone:'(206) 329-8700', notes:'Day center with family area. Meals, limited showers/laundry, computers, clothing bank, shelter referrals, case management. Focus on American Indian / Alaska Native community but open more broadly.', free:true, lat:47.5950, lon:-122.3200 , tags:['native']},
  { id:'r79', type:'daycenter', name:'Urban Rest Stop — Ballard', hours:'Mon–Fri 6:30am–1:30pm (with midday close)', addr:'2014B NW 57th St, Seattle, WA', phone:'(206) 258-3626', notes:'Second Urban Rest Stop location. Restrooms, showers, laundry. Same-day sign-up. Toiletries provided.', free:true, lat:47.6700, lon:-122.3850 },
  { id:'r80', type:'daycenter', name:'Salvation Army Jefferson Day Center', hours:'Daily 7am–5pm (including holidays)', addr:'420 4th Ave, Seattle, WA', phone:'(206) 338-5707', notes:'Shower, laundry, shelter navigation. First-come referrals to Salvation Army enhanced shelters with case management and meals.', free:true, lat:47.6020, lon:-122.3290 },

  // ---- Free meals / soup kitchens ----
  { id:'r10', type:'meal', name:'Union Gospel Mission — Seattle', hours:'Every day, breakfast 7am, dinner 5:30pm', addr:'318 2nd Ave Ext S, Seattle, WA', phone:'(206) 622-5177', notes:'Walk-in meals, no ID or registration needed.', free:true, lat:47.6014, lon:-122.3320 },
  { id:'r11', type:'meal', name:'Operation Sack Lunch', hours:'Every day, 12:00pm–1:00pm', addr:'1704 Fairview Ave E / Fisher Pavilion seasonal, Seattle, WA', phone:'(206) 328-2018', notes:'Hot lunch served daily — check current site posted at entrance or call.', free:true, lat:47.6205, lon:-122.3268 },
  { id:'r12', type:'meal', name:'Saint Martin de Porres Shelter — Meals', hours:'Every day, dinner 5:00pm', addr:'1561 Alaskan Way S, Seattle, WA', phone:'(206) 622-7307', notes:'Meal service connected to overnight shelter for men.', free:true, lat:47.5810, lon:-122.3400 },
  { id:'r13', type:'meal', name:'Nickelsville Meal Program', hours:'Varies by site — call ahead', addr:'Multiple locations, Seattle, WA', phone:'(206) 856-1211', notes:'Community-run meal support at various tiny house village sites.', free:true, lat:47.5600, lon:-122.3050 },
  { id:'r14', type:'meal', name:'St. James Cathedral — Community Meal', hours:'Sundays, 1:00pm', addr:'804 9th Ave, Seattle, WA', phone:'(206) 622-3559', notes:'Weekly community meal, open to all, no questions asked.', free:true, lat:47.6089, lon:-122.3253 },
  { id:'r81', type:'meal', name:'Operation Nightwatch Dinner', hours:'Every night 8:00pm–9:15pm', addr:'302 14th Ave S, Seattle, WA', phone:'(206) 323-4359', notes:'Free dinner for up to 150 people. No ID required.', free:true, lat:47.6018, lon:-122.3145 },
  { id:'r82', type:'meal', name:'Community Lunch on Capitol Hill', hours:'Check current schedule', addr:'509 10th Ave E, Seattle, WA', phone:'(206) 972-2524', notes:'Hot nutritious meals + clothing and other services for people experiencing homelessness or economic hardship.', free:true, lat:47.6235, lon:-122.3195 },
  { id:'r83', type:'meal', name:'Compass Day Center Meals', hours:'Lunch & dinner Mon–Fri; lunch Sat', addr:'210 Alaskan Way S, Seattle, WA', phone:'(206) 474-1630', notes:'Free meals for single adults using the day center.', free:true, lat:47.6010, lon:-122.3355 },

  // ---- Food banks and pantries ----
  { id:'r15', type:'foodbank', name:'University District Food Bank', hours:'Tue/Thu/Sat, 10:00am–1:00pm', addr:'5017 Roosevelt Way NE, Seattle, WA', phone:'(206) 523-7060', notes:'Choice-model food bank — pick what you need. No ID required for basic service.', free:true, lat:47.6621, lon:-122.3168 },
  { id:'r16', type:'foodbank', name:'Ballard Food Bank', hours:'Mon/Wed/Fri, 10:00am–1:00pm; Tue/Thu 3:00pm–6:00pm', addr:'1400 NW Leary Way, Seattle, WA', phone:'(206) 783-8302', notes:'Fresh produce, groceries, and hygiene items. Delivery available for those unable to travel.', free:true, lat:47.6656, lon:-122.3766 },
  { id:'r17', type:'foodbank', name:'White Center Food Bank', hours:'Mon–Fri, 10:00am–2:00pm', addr:'10829 8th Ave SW, Seattle, WA', phone:'(206) 762-0728', notes:'Serves White Center / South Park area, groceries and produce.', free:true, lat:47.5088, lon:-122.3390 },
  { id:'r18', type:'foodbank', name:'Rainier Valley Food Bank', hours:'Tue–Sat, 11:00am–3:00pm', addr:'3515 S Alaska St, Seattle, WA', phone:'(206) 723-4105', notes:'Culturally specific food options for the Rainier Valley community.', free:true, lat:47.5567, lon:-122.2860 },
  { id:'r84', type:'foodbank', name:'Pike Market Food Bank', hours:'Check current hours', addr:'Near Pike Place Market, Seattle, WA (98101/04/21 focus)', phone:'Call 211 or local listings', notes:'Serves downtown zip codes and people experiencing homelessness in the core.', free:true, lat:47.6095, lon:-122.3420 },
  { id:'r85', type:'foodbank', name:'Byrd Barr Place Food Bank', hours:'Check current; delivery for some zips', addr:'Central Seattle area (98102/12/22 focus)', phone:'Call 211', notes:'Healthy food + non-grocery essentials. Home delivery for qualifying zip codes.', free:true, lat:47.6200, lon:-122.3100 },
  { id:'r86', type:'foodbank', name:'North Helpline Food Bank', hours:'Check current hours', addr:'North Seattle / Shoreline area', phone:'Call 211', notes:'Food assistance + delivery for northern zip codes.', free:true, lat:47.7200, lon:-122.3200 },
  { id:'r87', type:'foodbank', name:'Seattle Indian Center Food Bank & Meals', hours:'Food bank Tue/Thu 1–3pm; meals Mon–Fri breakfast & lunch', addr:'624 S Dearborn St, Seattle, WA', phone:'(206) 329-8700', notes:'Food bank serving AI/AN community and others + daily hot meals and day center.', free:true, lat:47.5950, lon:-122.3200 },

  // ---- Showers and laundry ----
  { id:'r19', type:'shower', name:'Urban Rest Stop — Showers & Laundry (Downtown)', hours:'Mon–Fri early morning to afternoon/evening; weekends shorter', addr:'1924/1925 9th Ave, Seattle, WA', phone:'(206) 623-6675 or (206) 332-0110', notes:'Free showers, restrooms, and laundry. Towels and basic toiletries provided. One load every other day typical.', free:true, lat:47.6165, lon:-122.3352 },
  { id:'r20', type:'shower', name:'Queen Anne Community Center — Shower & Laundry Program', hours:'Wed & Fri, 9:00am–12:00pm', addr:'1901 1st Ave W, Seattle, WA', phone:'(206) 386-4240', notes:'Free showers and laundry for people experiencing homelessness. Sign-in at front desk.', free:true, lat:47.6297, lon:-122.3595 },
  { id:'r21', type:'shower', name:'Ballard Community Center — Shower Program', hours:'Tue & Thu, 9:00am–11:00am', addr:'6020 28th Ave NW, Seattle, WA', phone:'(206) 684-4093', notes:'Free showers, sign in with front desk staff.', free:true, lat:47.6721, lon:-122.3835 },
  { id:'r88', type:'shower', name:'Compass Hygiene Center', hours:'Mon–Fri 8:30am–4pm; Sat 8am–12pm', addr:'210 Alaskan Way S, Seattle, WA', phone:'(206) 474-1680', notes:'Showers, laundry, restrooms, hygiene packets, nurse care. Core Pioneer Square hygiene site.', free:true, lat:47.6010, lon:-122.3355 },
  { id:'r89', type:'shower', name:'City of Seattle Mobile Shower Trailers', hours:'Varies by weekly schedule — call for locations', addr:'Rotating sites citywide', phone:'(206) 386-1030', notes:'Free hot showers in trailers (standard + ADA stalls). Towels, soap, shampoo provided. Pets can be secured. Check current weekly locations.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'r90', type:'shower', name:'Dave\'s Day Center Showers & Laundry', hours:'Mon–Fri 8am–2pm', addr:'1215 Thomas St, Seattle, WA', phone:'(206) 622-1930', notes:'Industrial washers/dryers + showers + toiletries. Larger items (blankets) some days.', free:true, lat:47.6205, lon:-122.3370 },
  { id:'r91', type:'shower', name:'Community Center Hygiene Programs (multiple)', hours:'Varies: Delridge, Green Lake, Meadowbrook, Miller, Rainier, etc.', addr:'Various Seattle Parks community centers', phone:'Individual center numbers or 211', notes:'Several community centers offer free or low-barrier shower access for unhoused people on set days/hours. Confirm current schedule via 211 or center.', free:true, lat:47.6062, lon:-122.3321 },

  // ---- Clothing and hygiene ----
  { id:'r22', type:'clothing', name:'Facing Homelessness — Clothing Closet', hours:'Sat, 12:00pm–3:00pm', addr:'1907 NW 56th St, Seattle, WA', phone:'(206) 356-5964', notes:'Free clothing, sleeping bags, and hygiene kits distributed weekly.', free:true, lat:47.6685, lon:-122.3835 },
  { id:'r23', type:'clothing', name:'St. Vincent de Paul — Clothing Bank', hours:'Mon–Fri, 9:00am–3:00pm', addr:'5041 4th Ave S, Seattle, WA', phone:'(206) 767-6449', notes:'Free clothing for those in need, including work-appropriate items.', free:true, lat:47.5560, lon:-122.3260 },
  { id:'r92', type:'clothing', name:'Bread of Life Clothing & Day Services', hours:'Mon–Fri 9:30am–3pm', addr:'97 S Main St, Seattle, WA', phone:'(206) 682-3579', notes:'Clothing, lockers, showers, service referrals, mail.', free:true, lat:47.6005, lon:-122.3345 },

  // ---- Medical, dental, mental health ----
  { id:'r24', type:'medical', name:'Harborview Medical Center — ER', hours:'24/7', addr:'325 9th Ave, Seattle, WA', phone:'(206) 744-3000', notes:'Cannot turn away emergency care for inability to pay. Level 1 trauma center.', free:false, lat:47.6041, lon:-122.3231 },
  { id:'r25', type:'medical', name:'Neighborcare Health at Pioneer Square', hours:'Mon–Fri, 8:00am–5:00pm', addr:'206 3rd Ave S, Seattle, WA', phone:'(206) 296-4470', notes:'Sliding-scale clinic, medical care regardless of insurance or documentation status.', free:false, lat:47.5990, lon:-122.3320 },
  { id:'r26', type:'medical', name:'Public Health — Downtown Public Health Center', hours:'Mon–Fri, 8:00am–4:30pm', addr:'2124 4th Ave, Seattle, WA', phone:'(206) 296-4600 or (206) 477-8300', notes:'STD testing, immunizations, general public health, dental, maternity, WIC, Bupe on sliding scale.', free:false, lat:47.6142, lon:-122.3421 },
  { id:'r27', type:'dental', name:'Neighborcare Health Dental — Pioneer Square', hours:'Mon–Fri, 8:00am–5:00pm', addr:'206 3rd Ave S, Seattle, WA', phone:'(206) 296-4470', notes:'Sliding-scale dental care, walk-ins accepted for urgent pain.', free:false, lat:47.5990, lon:-122.3320 },
  { id:'r28', type:'mentalhealth', name:'DESC Crisis Solutions Center', hours:'24/7', addr:'1600 9th Ave, Seattle, WA', phone:'(206) 302-8000', notes:'Short-term crisis stabilization and mental health support, walk-ins and referrals both accepted.', free:true, lat:47.6156, lon:-122.3298 },
  { id:'r29', type:'mentalhealth', name:'Crisis Connections — 24-Hour Crisis Line', hours:'24/7 phone line', addr:'Phone service, Seattle, WA', phone:'(206) 461-3222', notes:'Free, confidential crisis support by phone, any time day or night.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'r93', type:'medical', name:'King County Street Medicine / Mobile Medical Van', hours:'Varies — check kingcounty.gov/streetmed', addr:'Rotating street & encampment locations', phone:'(206) 840-8737', notes:'Mobile medical care brought to people where they are. Wound care, basic primary care, referrals.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'r94', type:'medical', name:'Harborview Medical Respite (see also shelters)', hours:'Referral from hospital/clinic', addr:'800 Jefferson St, Seattle, WA', phone:'(206) 744-5200', notes:'Medical respite for those too ill for shelter but not needing full hospital.', free:false, lat:47.6045, lon:-122.3235 },

  // ---- Substance use / recovery ----
  { id:'r30', type:'recovery', name:'Evergreen Treatment Services', hours:'Mon–Fri, 5:30am–2:00pm', addr:'1700 Airport Way S, Seattle, WA', phone:'(206) 447-1712', notes:'Opioid treatment program including methadone and buprenorphine.', free:false, lat:47.5850, lon:-122.3260 },
  { id:'r31', type:'recovery', name:'REACH — Evergreen Treatment Services Outreach', hours:'Mon–Fri, 9:00am–5:00pm', addr:'1700 Airport Way S, Seattle, WA', phone:'(206) 434-7248', notes:'Street outreach and harm reduction services, syringe exchange, naloxone.', free:true, lat:47.5850, lon:-122.3260 },
  { id:'r32', type:'recovery', name:'People\'s Harm Reduction Alliance', hours:'Mon–Fri, 12:00pm–4:00pm', addr:'2314 3rd Ave, Seattle, WA', phone:'(206) 329-1720', notes:'Syringe exchange, naloxone kits, and harm reduction supplies, no judgment.', free:true, lat:47.6152, lon:-122.3450 },
  { id:'r95', type:'recovery', name:'Telebuprenorphine Hotline', hours:'Daily treatment access 9am–9pm; crisis support after hours via Recovery Helpline', addr:'Phone / telehealth', phone:'(206) 289-0287', notes:'Low-barrier medication for opioid use disorder via free telehealth visit. 24/7 crisis backup via WA Recovery Helpline.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'r96', type:'recovery', name:'King County Emergency Service Patrol (ESP / Detox Van)', hours:'24/7 in downtown core', addr:'Request via 911 (ask for Detox Van)', phone:'911 (request ESP/Detox Van)', notes:'Transport for intoxicated people to sobering services, supportive housing, non-emergency hospital, or crisis care. Operates primarily downtown Seattle.', free:true, lat:47.6062, lon:-122.3321 },

  // ---- Case management / street outreach ----
  { id:'r33', type:'outreach', name:'REACH Street Outreach', hours:'Mon–Fri, 9:00am–5:00pm', addr:'Citywide — call to connect', phone:'(206) 434-7248', notes:'Outreach workers can meet you where you are and connect you to shelter, healthcare, and housing.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'r34', type:'outreach', name:'DESC Case Management', hours:'Mon–Fri, 8:00am–5:00pm', addr:'517 3rd Ave, Seattle, WA', phone:'(206) 464-1570', notes:'Ongoing case management for housing, benefits, and healthcare navigation.', free:true, lat:47.6027, lon:-122.3305 },
  { id:'r97', type:'outreach', name:'Chief Seattle Club Outreach', hours:'Business hours', addr:'Citywide + day center', phone:'(206) 715-7536', notes:'Connects Native community members on the streets to shelters and services including Mary’s Place and UGM.', free:true, lat:47.6008, lon:-122.3325 },

  // ---- Housing navigation / rapid rehousing / vouchers ----
  { id:'r35', type:'housinghelp', name:'Family Housing Connection / Mary’s Place Access', hours:'Mon–Fri phone + daily shelter line from 9am', addr:'Phone & online intake', phone:'(206) 245-1026', notes:'Coordinated entry point for family shelter and housing programs across King County.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'r36', type:'housinghelp', name:'Catholic Community Services — Housing Case Management + RAP', hours:'Mon–Fri, 9:00am–5:00pm (often appointment)', addr:'100 23rd Ave S, Seattle, WA', phone:'(206) 328-5900 or (206) 328-5696', notes:'Rapid rehousing, rental support navigation, and one of the primary Regional Access Points for Coordinated Entry.', free:true, lat:47.6005, lon:-122.2980 },
  { id:'r37', type:'housinghelp', name:'Seattle Housing Authority — Voucher Info', hours:'Mon–Fri, 8:00am–5:00pm', addr:'190 Queen Anne Ave N, Seattle, WA', phone:'(206) 239-1728', notes:'Housing Choice Voucher (Section 8) waitlist and application info.', free:true, lat:47.6235, lon:-122.3570 },
  { id:'r38', type:'housinghelp', name:'Plymouth Housing — Housing Placement', hours:'Mon–Fri, 9:00am–4:00pm', addr:'2400 3rd Ave, Seattle, WA', phone:'(206) 441-4540', notes:'Permanent supportive housing placement for adults exiting homelessness.', free:true, lat:47.6152, lon:-122.3450 },
  { id:'r98', type:'housinghelp', name:'Solid Ground — North Seattle RAP + Benefits', hours:'Mon–Fri 9am–5pm; walk-in Wed 11am–1pm limited', addr:'1501 N 45th St, Seattle, WA', phone:'(206) 694-6833 or (206) 694-6700', notes:'Regional Access Point for Coordinated Entry + benefits navigation (SNAP, ABD, etc.).', free:true, lat:47.6612, lon:-122.3352 },
  { id:'r99', type:'housinghelp', name:'Other King County Regional Access Points', hours:'Varies (Federal Way, Renton, Bellevue/East, etc.)', addr:'Multiple South & East King County sites', phone:'Call 211 or see kcrha.org/regional-access-points', notes:'Anyone in King County can use any RAP. Walk-in hours limited; appointments preferred. Entry point to housing prioritization.', free:true, lat:47.5000, lon:-122.3000 },

  // ---- ID and document replacement ----
  { id:'r39', type:'documents', name:'WA Department of Licensing — Seattle Office', hours:'Mon–Fri, 8:00am–5:00pm', addr:'1000 2nd Ave, Seattle, WA', phone:'(360) 902-3900', notes:'State ID replacement. Ask about the fee waiver for people experiencing homelessness.', free:false, lat:47.6062, lon:-122.3358 },
  { id:'r40', type:'documents', name:'DESC — ID Assistance Program', hours:'Mon–Fri, 9:00am–4:00pm', addr:'517 3rd Ave, Seattle, WA', phone:'(206) 464-1570', notes:'Staff can help gather documents and write identity confirmation letters.', free:true, lat:47.6027, lon:-122.3305 },
  { id:'r41', type:'documents', name:'WA Vital Records — Birth Certificates', hours:'Mon–Fri, 8:00am–5:00pm (phone/online)', addr:'Phone & online service', phone:'(360) 236-4300', notes:'Order a replacement birth certificate; reduced fee available for people experiencing homelessness.', free:false, lat:47.6062, lon:-122.3321 },

  // ---- Mail and address services ----
  { id:'r42', type:'mail', name:'Compass Housing Alliance — Mail Program', hours:'Mon–Fri, 9:00am–4:00pm', addr:'77 S Washington St / 210 Alaskan Way, Seattle, WA', phone:'(206) 474-1000 or (206) 474-1630', notes:'Free mail receiving service — get a stable address to receive mail and benefits letters.', free:true, lat:47.6008, lon:-122.3330 },
  { id:'r43', type:'mail', name:'Urban Rest Stop — Mail Services', hours:'During day center hours', addr:'1924 9th Ave, Seattle, WA', phone:'(206) 623-6675', notes:'Mail pickup service for people without a fixed address.', free:true, lat:47.6165, lon:-122.3352 },
  { id:'r100', type:'mail', name:'Chief Seattle Club Mail', hours:'During day center hours', addr:'410 2nd Ave area, Seattle, WA', phone:'(206) 715-7536', notes:'Mail services for members.', free:true, lat:47.6008, lon:-122.3325 },

  // ---- Storage lockers ----
  { id:'r44', type:'storage', name:'Urban Rest Stop — Storage Lockers', hours:'During day center hours', addr:'1924 9th Ave, Seattle, WA', phone:'(206) 623-6675', notes:'Free daily-use lockers for personal belongings.', free:true, lat:47.6165, lon:-122.3352 },
  { id:'r45', type:'storage', name:'Public Library — Central Branch Lockers', hours:'Library hours, Mon–Sun', addr:'1000 4th Ave, Seattle, WA', phone:'(206) 386-4636', notes:'Free daily lockers, sign out a key at the front desk. Not for overnight storage.', free:true, lat:47.6067, lon:-122.3327 },
  { id:'r101', type:'storage', name:'SHARE/WHEEL Storage Lockers', hours:'Tue/Thu 7–9am; Sat/Sun 8–10am (confirm)', addr:'711 Cherry St, Seattle, WA', phone:'(206) 448-7889', notes:'Day and longer-term storage lockers (large duffle size) for people experiencing homelessness who can provide labor.', free:true, lat:47.6055, lon:-122.3250 },

  // ---- Phone charging / free wifi ----
  { id:'r46', type:'charging', name:'Seattle Public Library — Central Branch', hours:'Mon–Thu 10am–8pm, Fri–Sat 10am–6pm, Sun 12pm–6pm', addr:'1000 4th Ave, Seattle, WA', phone:'(206) 386-4636', notes:'Free Wi-Fi, phone charging outlets, and public computers.', free:true, lat:47.6067, lon:-122.3327 },
  { id:'r47', type:'charging', name:'Urban Rest Stop — Charging Station', hours:'During day center hours', addr:'1924 9th Ave, Seattle, WA', phone:'(206) 623-6675', notes:'Free phone charging while you wait for showers or laundry.', free:true, lat:47.6165, lon:-122.3352 },

  // ---- Water ----
  { id:'r48', type:'water', name:'Occidental Park Fountain', hours:'Always open', addr:'Occidental Ave S, Seattle, WA', notes:'Free drinking water fountain in Pioneer Square.', free:true, lat:47.5997, lon:-122.3339 },
  { id:'r49', type:'water', name:'Seattle Public Library — Central Branch', hours:'Library hours', addr:'1000 4th Ave, Seattle, WA', notes:'Water fountain and bottle refill station, restrooms available.', free:true, lat:47.6067, lon:-122.3327 },

  // ---- Day labor / temp work ----
  { id:'r150', type:'work', name:'Millionair Club Charity — Day Labor (Uplift Northwest)', hours:'Check-in from 5:30am, Mon–Fri', addr:'2515 Western Ave, Seattle, WA', phone:'(206) 728-2213', pay:'Cash or check, paid same day', notes:'Landscaping, moving, warehouse, and event setup work. Long-running, respected Seattle program — no fee to use. Also offers career training and locker services at some sites.', free:true, lat:47.6157, lon:-122.3540 },
  { id:'r151', type:'work', name:'WorkSource Seattle — King County', hours:'Mon–Fri, 8:30am–4:30pm', addr:'2003 Western Ave, Seattle, WA', phone:'(206) 436-8600', pay:'Varies by placement', notes:'Free job search assistance, resume help, and referrals to local employers hiring now.', free:true, lat:47.6099, lon:-122.3468 },
  { id:'r152', type:'work', name:'Seattle Farmers Markets — Setup Crews', hours:'Varies by market day (Sat mornings common)', addr:'Various neighborhood markets, Seattle, WA', pay:'Tips, sometimes $15–20 flat', notes:'Ask any market vendor about early morning setup help — tips are common and some pay a flat rate.', free:true, lat:47.6205, lon:-122.3493 },
  { id:'r153', type:'work', name:'Uplift Northwest — Additional Programs', hours:'Mon–Fri daytime', addr:'2515 Western Ave area, Seattle, WA', phone:'(206) 728-2213 or (206) 728-5627', pay:'Varies by program', notes:'Beyond day labor: career training, housing referrals, locker services. Same organization family as Millionair Club.', free:true, lat:47.6157, lon:-122.3540 },
  { id:'r154', type:'work', name:'SODO Staffing Agencies — Day Labor Desks', hours:'Check in early, Mon–Fri', addr:'Multiple SODO-area locations, Seattle, WA', pay:'Varies, often $19–23/hr', notes:'Several temp staffing agencies in the SODO industrial area post same-day warehouse and light industrial work. Walk in early morning and ask about day labor.', free:true, lat:47.5750, lon:-122.3300 },

  // ---- Legal aid ----
  { id:'r52', type:'legal', name:'Northwest Justice Project', hours:'Mon–Fri, 9:00am–5:00pm (phone intake)', addr:'401 2nd Ave S, Seattle, WA', phone:'(888) 201-1014', notes:'Free civil legal aid: eviction defense, benefits denials, ID recovery help.', free:true, lat:47.5996, lon:-122.3310 },
  { id:'r53', type:'legal', name:'King County Bar Association — Housing Justice Project', hours:'Mon–Fri, 9:00am–4:00pm', addr:'516 3rd Ave, Seattle, WA', phone:'(206) 267-7069', notes:'Free legal help specifically for eviction and housing court cases.', free:true, lat:47.6032, lon:-122.3303 },

  // ---- Pet-friendly ----
  { id:'r54', type:'pets', name:'Seattle Humane — Pet Support Pantry', hours:'By appointment, call ahead', addr:'13212 SE Eastgate Way, Bellevue, WA', phone:'(425) 649-7550', notes:'Free pet food pantry for owners facing hardship, including people experiencing homelessness.', free:true, lat:47.5773, lon:-122.1425 },
  { id:'r55', type:'pets', name:'DESC Shelter — Pet-Friendly Space', hours:'Every night, doors 4:00pm', addr:'517 3rd Ave, Seattle, WA', phone:'(206) 464-1570', notes:'One of the few shelters that allows pets to stay with their owner. Ask at intake.', free:true, lat:47.6027, lon:-122.3305 , tags:['pet']},
  { id:'r102', type:'pets', name:'New Horizons & some YA programs', hours:'Varies', addr:'See youth shelter entries', phone:'See youth numbers', notes:'Several young adult shelters allow pets — confirm at intake (New Horizons noted as pet-friendly).', free:true, lat:47.6175, lon:-122.3455 },

  // ---- Warming / cooling centers ----
  { id:'r56', type:'warming', name:'City of Seattle Warming Center Network', hours:'Opens when temps drop below ~33°F or during winter storms', addr:'Multiple sites — check current locations via 211 or seattle.gov', phone:'(206) 684-3000 or 211', notes:'Extra emergency shelter space that opens automatically on cold nights. No registration needed. Always verify current activation.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'r57', type:'warming', name:'Seattle Cooling Centers', hours:'Opens during heat emergencies, summer months', addr:'Multiple library & community center sites', phone:'(206) 684-3000 or 211', notes:'Air-conditioned public spaces that open during extreme heat. Libraries often serve this role.', free:true, lat:47.6062, lon:-122.3321 },

  // ---- Library services ----
  { id:'r58', type:'library', name:'Seattle Public Library — Ballard Branch', hours:'Mon–Thu 10am–8pm, Fri–Sat 10am–6pm', addr:'5614 22nd Ave NW, Seattle, WA', phone:'(206) 684-4089', notes:'Free computers, printing (small fee per page), Wi-Fi, and a quiet place to rest.', free:true, lat:47.6685, lon:-122.3835 },
  { id:'r59', type:'library', name:'Seattle Public Library — Capitol Hill Branch', hours:'Mon–Thu 10am–8pm, Fri–Sat 10am–6pm', addr:'425 Harvard Ave E, Seattle, WA', phone:'(206) 684-4715', notes:'Public computers and printing, plus community programs.', free:true, lat:47.6236, lon:-122.3218 },
  { id:'r103', type:'library', name:'Seattle Public Library — Central Branch (full services)', hours:'Mon–Thu 10am–8pm, Fri–Sat 10am–6pm, Sun 12–6pm', addr:'1000 4th Ave, Seattle, WA', phone:'(206) 386-4636', notes:'Wi-Fi, charging, computers, lockers, water, restrooms, quiet space. Major daytime resource hub.', free:true, lat:47.6067, lon:-122.3327 },

  // ---- Benefits enrollment help ----
  { id:'r60', type:'benefits', name:'DSHS Community Services Office — Downtown Seattle', hours:'Mon–Fri, 8:00am–5:00pm', addr:'1901 Martin Luther King Jr Way S, Seattle, WA', phone:'(877) 501-2233', notes:'Apply for SNAP (food stamps), cash assistance, and Medicaid in person or get help with your application.', free:true, lat:47.5828, lon:-122.2990 },
  { id:'r61', type:'benefits', name:'Solid Ground — Benefits Navigator', hours:'Mon–Fri, 9:00am–4:00pm', addr:'1501 N 45th St, Seattle, WA', phone:'(206) 694-6700', notes:'Free help applying for SNAP, ABD cash, and other public benefits.', free:true, lat:47.6612, lon:-122.3352 },

  // ---- Transportation ----
  { id:'r104', type:'transport', name:'ORCA Reduced Fare / LIFT / RRFP', hours:'Apply online or at retail locations; libraries often help', addr:'King County Metro / ORCA system', phone:'211 or Metro customer service', notes:'Reduced-fare ORCA cards for low-income (ORCA LIFT) and seniors/disabled (RRFP). Critical for getting to appointments and jobs. Many day centers and libraries help with applications.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'r105', type:'transport', name:'HopeLink / Medicaid Non-Emergency Medical Transport', hours:'By appointment for Medicaid-funded medical trips', addr:'Phone-based', phone:'(800) 923-7433', notes:'Rides (bus fare, gas, or vehicle) to and from Medicaid-covered medical appointments for eligible people.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'r106', type:'transport', name:'Vehicle Resident Outreach (City of Seattle HSD)', hours:'Business hours; call to request neighborhood team', addr:'Citywide for people living in vehicles', phone:'(206) 600-8486 or (206) 507-9428', notes:'Dedicated outreach for people living in cars/RVs. Help with parking tickets (payment plans, reductions), legal parking info, vehicle repairs, and connections to safe lots / housing. Tell them where you are parked.', free:true, lat:47.6062, lon:-122.3321 },

  // ---- Safe parking / vehicle residency ----
  { id:'r107', type:'safeparking', name:'Urban League of Metropolitan Seattle — Road to Housing Safe Parking', hours:'Overnight safe lots (confirm current sites)', addr:'Multiple lots in north, west, and central Seattle', phone:'Contact Urban League main office for intake packet', notes:'Safe overnight parking for people living in cars (not RVs at most sites). Amenities may include restrooms, showers, kitchen, laundry. Goal is transition to permanent housing. Intake packet required.', free:true, lat:47.6200, lon:-122.3500 , tags:['vehicle']},
  { id:'r108', type:'safeparking', name:'Our Redeemer’s Lutheran Church / Urban League Safe Parking (Ballard)', hours:'Overnight', addr:'Ballard area (confirm with program)', phone:'Via Urban League or church', notes:'City-supported expansion of Road to Housing safe parking. Limited spots, restrooms, showers, small kitchen, laundry.', free:true, lat:47.6680, lon:-122.3850 },
  { id:'r109', type:'safeparking', name:'Family Promise of Puget Sound — Safe Parking (Families)', hours:'6:00pm–8:00am daily', addr:'Confirm current site', phone:'See fpops.org or call 211', notes:'Safe overnight parking specifically for families with children. Kitchen access, bathrooms, hygiene. Requires vehicle registration, insurance, consultation, and background screening.', free:true, lat:47.5500, lon:-122.3000 , tags:['vehicle', 'family', 'hasKids']},
  { id:'r110', type:'safeparking', name:'Other King County Safe Parking (Overlake, St. John, Newport, etc.)', hours:'Varies by site', addr:'Eastside and other King County church/community lots', phone:'211 or KCRHA vehicle residency page', notes:'Several church-based safe parking programs (cars only at most). Access to showers, meals, case management at some. Call 211 for current openings and requirements.', free:true, lat:47.6200, lon:-122.2000 },
  { id:'r111', type:'safeparking', name:'LIHI RV / Vehicle Safe Lot (status variable)', hours:'When operating — check current location', addr:'Previously Interbay / seeking new sites', phone:'(206) 620-7130 (LIHI)', notes:'LIHI has operated RV safe lots (e.g. Salmon Bay Village) with high housing-exit rates. Locations change; ask LIHI or Vehicle Resident Outreach for current status.', free:true, lat:47.6400, lon:-122.3800 },

  // ---- Domestic violence / confidential shelters ----
  { id:'r112', type:'shelter', name:'ADWAS — Abused Deaf Women\'s Advocacy Services', hours:'Mon–Fri 9am–5pm (closed 12–1); 24/7 crisis support via partners', addr:'Confidential location', phone:'(206) 922-7088 (TTY/VP)', notes:'Domestic violence shelter fully accessible for Deaf, Deafblind, or hard-of-hearing women. Confidential.', free:true, lat:47.6062, lon:-122.3321 , tags:['dv', 'woman']},
  { id:'r113', type:'shelter', name:'Broadview / Solid Ground DV Shelter', hours:'24 hours daily, call for intake', addr:'Confidential', phone:'(206) 299-2500', notes:'Confidential shelter for survivor-headed families with children. Serves trans clients who identify as female or male who have children.', free:true, lat:47.6062, lon:-122.3321 , tags:['dv', 'family']},
  { id:'r114', type:'shelter', name:'DAWN (Domestic Abuse Women’s Network)', hours:'24 hours daily, call for intake', addr:'Confidential (South King focus)', phone:'(425) 656-7867 or 1-877-465-7234', notes:'Confidential shelter for people who identify as women (with or without children) fleeing DV. Pets/service animals accepted at some. No ID or DV documentation required.', free:true, lat:47.3800, lon:-122.2300 , tags:['dv', 'woman']},
  { id:'r115', type:'shelter', name:'LifeWire — My Sister’s Home', hours:'24 hours daily, call for intake', addr:'Confidential (East King)', phone:'(425) 562-8840 or 1-800-827-8840', notes:'Confidential emergency shelter for survivors of any gender or non-binary, with or without children.', free:true, lat:47.6100, lon:-122.2000 , tags:['dv']},
  { id:'r116', type:'shelter', name:'New Beginnings', hours:'24 hours daily, call for intake', addr:'Confidential (Seattle / North King)', phone:'(206) 522-9472 or (206) 737-0242', notes:'Confidential short-term housing for survivors of any gender, with or without children. Also community advocacy and legal advocacy.', free:true, lat:47.6800, lon:-122.3200 , tags:['dv']},
  { id:'r117', type:'shelter', name:'YWCA Domestic Violence Services', hours:'DV shelter intake line available', addr:'Multiple / confidential', phone:'(206) 461-4882 (shelter intake)', notes:'Advocacy, counseling, housing, and children’s services for survivors. Multiple languages available.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'r118', type:'system', name:'King County / Seattle DV Hotline', hours:'24/7', addr:'Phone', phone:'1-877-737-0242 or dvhopeline.org', notes:'Central 24/7 domestic violence hotline for Seattle–King County. Can provide information on confidential shelter availability and safety planning.', free:true, lat:47.6062, lon:-122.3321 , tags:['dv']},

  // ---- Sobering / post-overdose / detox ----
  { id:'r119', type:'recovery', name:'King County Sobering Center (Pioneer Human Services)', hours:'24/7 when permanent SODO site open; temporary Yesler previously 5pm–7am', addr:'1950 1st Ave S (SODO permanent site) or current temporary', phone:'(206) 349-0165 (Diversion Center line) or via ESP/911', notes:'Safe place to sleep off acute alcohol/drug intoxication or post-opiate overdose. Medically monitored, case management, referrals to detox/treatment/housing. Walk-ins and ESP transports accepted. Capacity ~40 at permanent site.', free:true, lat:47.5850, lon:-122.3350 },
  { id:'r120', type:'recovery', name:'DESC ORCA Center — Opioid Recovery & Care Access', hours:'24/7 post-overdose stabilization; walk-in MOUD 9am–11pm', addr:'515 Third Ave (Morrison), Seattle, WA', phone:'DESC main or (206) 464-1570 area', notes:'Post-overdose stabilization (up to 8 people) + walk-in opioid use disorder treatment. Psychiatric assessment, nursing, case management, peer support. Designed as lower-barrier alternative to ER after overdose.', free:true, lat:47.6025, lon:-122.3310 },
  { id:'r121', type:'recovery', name:'Recovery Place Seattle (Beacon Hill) — Detox', hours:'Call for intake', addr:'1701 18th Ave S, Seattle, WA', phone:'(253) 833-7444', notes:'Medically supervised withdrawal management (detox) for alcohol and other drugs. Goal is stabilization then transition to ongoing care.', free:false, lat:47.5800, lon:-122.3100 },

  // ---- Additional youth / LGBTQ+ ----
  { id:'r122', type:'daycenter', name:'Lambert House LGBTQ Youth Center', hours:'Mon–Fri typically 4pm–9:30pm (confirm)', addr:'1229 10th Ave E, Seattle, WA', phone:'(206) 322-2515', notes:'Only King County agency solely dedicated to LGBTQ youth (mainly 10–17, also young adults). Meals, clothing, hygiene, peer support, mentoring, HIV/STI education, LGBTQ-competent housing/medical/mental health referrals, homeless services.', free:true, lat:47.6205, lon:-122.3200 , tags:['youth', 'lgbtq']},
  { id:'r123', type:'daycenter', name:'Street Youth Ministries (SYM) Drop-In', hours:'Mon–Fri 10am–1pm (confirm current)', addr:'University District, Seattle, WA', phone:'See symseattle.org', notes:'Drop-in for unhoused youth and young adults ages 13–26. Breakfast program, life skills, resources, affirming community in the U District.', free:true, lat:47.6600, lon:-122.3100 },
  { id:'r124', type:'shelter', name:'Urban League Young Adult Night Shelter', hours:'8pm–8am', addr:'Confirm current location via Urban League', phone:'Urban League main', notes:'12-hour night shelter for young adults 18–24. All genders/orientations welcome. Zero-tolerance for harmful behavior. Supports economic security and stability.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'r125', type:'daycenter', name:'PSKS — Peace for the Streets by Kids from the Streets', hours:'Check current', addr:'Seattle area', phone:'(206) 726-8500', notes:'Shelter and support for homeless youth and young adults. Education, employment, housing support. Prioritizes safety and security.', free:true, lat:47.6062, lon:-122.3321 },
  { id:'r126', type:'meal', name:'Teen Feed', hours:'Evening meal programs (confirm schedule)', addr:'University District and rotating', phone:'See teenfeed.org or 211', notes:'Meals and relationship-based support for homeless and street-involved youth. Allyship model.', free:true, lat:47.6600, lon:-122.3100 },

  // ---- Additional Native / Indigenous ----
  { id:'r127', type:'medical', name:'Seattle Indian Health Board', hours:'Clinic hours vary; DV support available', addr:'611 12th Ave S Suite 200, Seattle, WA', phone:'(206) 324-9360', notes:'Primary care, behavioral health, and domestic violence support for American Indian / Alaska Native community and others. Culturally grounded services.', free:false, lat:47.5980, lon:-122.3160 },
  { id:'r128', type:'daycenter', name:'Chief Seattle Club (expanded note)', hours:'See earlier day center entry', addr:'410 2nd Ave area', phone:'(206) 715-7536', notes:'Already listed under day centers. Strongest Native-specific day center + housing case management + outreach in downtown Seattle.', free:true, lat:47.6008, lon:-122.3325 },

  // ---- Additional clothing / hygiene / misc ----
  { id:'r129', type:'clothing', name:'St. Francis House', hours:'Mon–Fri 10am–2pm', addr:'169 12th Ave (near E Spruce), Seattle, WA', phone:'See listings or 211', notes:'Clothes and household goods. Photo ID often requested.', free:true, lat:47.6020, lon:-122.3170 },
  { id:'r130', type:'daycenter', name:'Solanus Casey Center (St. James)', hours:'Mon–Thu 1–4pm', addr:'804 9th Ave, Seattle, WA', phone:'(206) 223-0907', notes:'Hospitality and referrals: ORCA cards, vouchers, IDs, job assistance, transitional housing navigation.', free:true, lat:47.6089, lon:-122.3253 },
  { id:'r131', type:'daycenter', name:'Aurora Commons', hours:'Drop-in M–Th 10am–1pm; clinic days vary', addr:'8914 Aurora Ave N, Seattle, WA', phone:'(206) 299-2278', notes:'Drop-in, Aurora Clinic, SHE (Safe Healthy Empowered) Clinic. Support for people on the Aurora corridor.', free:true, lat:47.6940, lon:-122.3450 },
  { id:'r132', type:'daycenter', name:'Seattle Court Resource Center', hours:'Mon/Wed 8:30am–4pm (closed 12–1)', addr:'600 5th Ave, 2nd floor room 235, Seattle, WA', phone:'(206) 684-9291', notes:'Smartphone access, medication-assisted treatment connections, emergency food & clothes, resource navigation near the courthouse.', free:true, lat:47.6050, lon:-122.3295 },

  // ---- Additional meals / food ----
  { id:'r133', type:'meal', name:'FareStart Guest Meals / Community Meals', hours:'Check current public meal schedule', addr:'Various / FareStart locations', phone:'211 or farestart.org', notes:'FareStart and partner sites offer guest meals and community meal programs. Confirm current public access times.', free:true, lat:47.6100, lon:-122.3400 },
  { id:'r134', type:'foodbank', name:'Food Lifeline / Northwest Harvest (distribution partners)', hours:'Varies by partner pantry', addr:'Multiple King County sites', phone:'Food Lifeline (206) 545-6600; NW Harvest (206) 625-0755', notes:'Major food banks that supply dozens of local pantries. Call 211 or their lines for nearest open distribution.', free:true, lat:47.6062, lon:-122.3321 },

  // ---- Additional legal / reentry ----
  { id:'r135', type:'legal', name:'King County Bar / Housing Justice + broader civil', hours:'See earlier HJP entry', addr:'516 3rd Ave area', phone:'(206) 267-7069 (HJP)', notes:'Housing Justice Project already listed. Broader civil legal aid also available via Northwest Justice Project and 211 referrals.', free:true, lat:47.6032, lon:-122.3303 },
  { id:'r136', type:'outreach', name:'Reentry services (via 211 / DOC community partners)', hours:'Varies', addr:'Multiple', phone:'211', notes:'People exiting jail or prison can access specialized reentry case management, ID help, benefits enrollment, and housing navigation through 211 and DOC community partners. Ask specifically for reentry resources.', free:true, lat:47.6062, lon:-122.3321 },

  // ---- Senior-specific note ----
  { id:'r137', type:'housinghelp', name:'Senior housing & services (Plymouth, CCS, Operation Nightwatch senior housing)', hours:'Varies', addr:'Multiple', phone:'211 or listed agency numbers', notes:'Several programs prioritize or exclusively serve seniors (e.g. Operation Nightwatch permanent housing for 62+, St. Martin de Porres for men 50+, various CCS senior buildings). Call 211 and specify age for best matches.', free:true, lat:47.6062, lon:-122.3321 },

  // ---- Final system reminder ----
  { id:'r138', type:'system', name:'Always verify with 211 or the agency before traveling', hours:'24/7 automated + live Mon–Fri', addr:'Phone / web', phone:'211', notes:'Hours, bed availability, and program rules change frequently. Weather-activated centers, mobile showers, and safe parking spots open and close. When in doubt, call 211 or the listed number first.', free:true, lat:47.6062, lon:-122.3321 },

  // ---- Veterans-specific (high priority filter tag) ----
  { id:'r139', type:'system', name:'National Call Center for Homeless Veterans', hours:'24/7', addr:'Phone', phone:'(877) 424-3838', notes:'National VA hotline for veterans experiencing homelessness. Connects to local HUD-VASH, SSVF, and VA housing resources. Also try va.gov/homeless.', free:true, lat:47.6062, lon:-122.3321, tags:['veteran'] },
  { id:'r140', type:'system', name:'Veterans Crisis Line', hours:'24/7', addr:'Phone', phone:'988 then press 1 (or 1-800-273-8255 Ext 1)', notes:'24/7 confidential support for veterans in crisis. Free and confidential.', free:true, lat:47.6062, lon:-122.3321, tags:['veteran'] },
  { id:'r141', type:'housinghelp', name:'King County Veterans Program (KCVP)', hours:'Mon–Fri 8:30am–4:30pm; walk-in windows limited', addr:'9725 3rd Ave NE Suite 300, Seattle, WA (also Tukwila office)', phone:'(206) 263-8387 or (206) 477-8282', notes:'Case management, HUD-VASH coordination, SSVF referrals, benefits help, financial coaching for veterans experiencing or at risk of homelessness. Bring proof of service if possible (they can help obtain it).', free:true, lat:47.7000, lon:-122.3250, tags:['veteran'] },
  { id:'r142', type:'housinghelp', name:'VA Puget Sound Community Housing & Outreach Services (CHOS)', hours:'Business hours', addr:'VA Puget Sound system', phone:'(206) 764-5149', notes:'VA housing and outreach services for eligible veterans. Coordinates with HUD-VASH and community partners.', free:true, lat:47.5600, lon:-122.3000, tags:['veteran'] },
  { id:'r143', type:'housinghelp', name:'VA Community Resource & Referral Center (CRRC)', hours:'Mon–Fri 8:30–11:30am walk-in screening', addr:'305 S Lucile St, Seattle, WA', phone:'See VA or call 211', notes:'Walk-in screening for veteran housing programs, emergency shelter connections, case management. On-site partners include VBA and SSVF.', free:true, lat:47.5600, lon:-122.3200, tags:['veteran'] },
  { id:'r144', type:'housinghelp', name:'SSVF — Sound Veterans Services', hours:'Mon–Fri 9am–5pm (call to screen)', addr:'4636 East Marginal Way S Suite B-130, Seattle, WA (Georgetown)', phone:'(206) 545-2344', notes:'Supportive Services for Veteran Families: rapid re-housing, short-term case management, temporary financial assistance for veteran households experiencing or at imminent risk of homelessness in King County. Case managers meet in the community.', free:true, lat:47.5550, lon:-122.3350, tags:['veteran'] },
  { id:'r145', type:'housinghelp', name:'SSVF — Catholic Community Services', hours:'Call for appointment', addr:'Multiple (Kent, Rainier Ave S Seattle, etc.)', phone:'(206) 814-1660 (King County) or (253) 850-2507', notes:'SSVF rapid re-housing and homelessness prevention for veteran families and individuals. Short-term financial assistance + housing stability plans.', free:true, lat:47.5500, lon:-122.3000, tags:['veteran'] },
  { id:'r146', type:'housinghelp', name:'HUD-VASH (via VA + Housing Authorities)', hours:'Through VA / KCVP / SHA / KCHA', addr:'Coordinated via VA and housing authorities', phone:'Start with (877) 424-3838 or KCVP (206) 263-8387', notes:'Housing Choice Voucher + VA case management for homeless veterans. Entry is through VA eligibility and local Coordinated Entry / veteran navigators. Not a walk-in shelter.', free:true, lat:47.6062, lon:-122.3321, tags:['veteran'] },
  { id:'r147', type:'outreach', name:'Multi-Service Center — Veterans Navigation', hours:'By appointment + limited walk-in Coordinated Entry times', addr:'Federal Way / Auburn / Tukwila coordination', phone:'(253) 354-6204 (navigator) or MSC main', notes:'Veterans System Navigation Coordinator helps unhoused veterans connect to KCVP, HUD-VASH, SSVF, benefits, mental health, and housing. Proof of service helpful but they can assist obtaining it.', free:true, lat:47.3200, lon:-122.3100, tags:['veteran'] }
];

// Deprecated: kept only for backward compatibility with any code that
// still references SEATTLE_WORK directly. The real, canonical set of
// work/day-labor listings now lives inside SEATTLE_RESOURCES (type:'work')
// so they get full feature parity — GPS distance sort, favorites, notes,
// share, print, and map — just like every other resource category.
var SEATTLE_WORK = SEATTLE_RESOURCES.filter(function (r) { return r.type === 'work'; });
